version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: noharm_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: noharm
    ports:
      - "5432:5432"
    volumes:
      - noharm_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d noharm"]
      interval: 3s
      timeout: 5s
      retries: 10
volumes:
  noharm_test_data:
