name: Deploy Test (Manual)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: noharm
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Config Zappa
        run: |
          echo '${{ secrets.ZAPPA_TEST_SETTINGS }}' > zappa_settings.json 
          mkdir ~/.aws/ 
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region = sa-east-1" > ~/.aws/credentials
      - name: Deploy Zappa
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-prod.txt
          zappa update test -q
